#[derive(Debug)]
pub enum TxError {
    AccountIndexTooLow,
    AccountIndexTooHigh,
    NonceTooLow,
    ApiKeyIndexTooLow,
    ApiKeyIndexTooHigh,
    ExpiredAtInvalid,
    InvalidMarketIndex,
    InvalidSignature,
    FromAccountIndexTooLow,
    FromAccountIndexTooHigh,
    ToAccountIndexTooLow,
    ToAccountIndexTooHigh,
    AssetIndexTooLow,
    AssetIndexTooHigh,
    RouteTypeInvalid,
    TransferAmountTooLow,
    TransferAmountTooHigh,
    TransferFeeNegative,
    TransferFeeTooHigh,
    WithdrawalAmountTooLow,
    WithdrawalAmountTooHigh,
    PubKeyInvalid,
    ClientOrderIndexTooLow,
    ClientOrderIndexTooHigh,
    OrderIndexTooLow,
    OrderIndexTooHigh,
    BaseAmountTooLow,
    BaseAmountTooHigh,
    PriceTooLow,
    PriceTooHigh,
    IsAskInvalid,
    OrderTypeInvalid,
    OrderTimeInForceInvalid,
    OrderReduceOnlyInvalid,
    OrderTriggerPriceInvalid,
    OrderExpiryInvalid,
    CancelAllTimeInForceInvalid,
    CancelAllTimeNotInRange,
    BaseAmountsNotEqual,
    BaseAmountNotNil,
    MarketIndexMismatch,
    ClientOrderIndexDuplicate,
    GroupingTypeInvalid,
    OrderGroupSizeInvalid,
    InvalidMarginMode,
    MarginFractionTooLow,
    MarginFractionTooHigh,
    InvalidUpdateMarginDirection,
    PoolOperatorFeeInvalid,
    PoolStatusInvalid,
    InitialSharesTooLow,
    InitialSharesTooHigh,
    MinOperatorShareRateTooLow,
    MinOperatorShareRateTooHigh,
    MintShareAmountTooLow,
    MintShareAmountTooHigh,
    BurnShareAmountTooLow,
    BurnShareAmountTooHigh,
    StakeAmountTooLow,
    StakeAmountTooHigh,
    UnstakeAmountTooLow,
    UnstakeAmountTooHigh,
    IntegratorAccountIndexTooLow,
    IntegratorAccountIndexTooHigh,
    FeeTooHigh,
    ApprovalExpiryInvalid,
    ApprovalExpiryZeroOnRevocation,
    TooManyAttributes,
    InvalidAttributeType,
    AttributeValueOutOfRange,
    IntegratorAccountIndexRequired,
    NonceSkipAttributeInvalid,
}

impl std::fmt::Display for TxError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::AccountIndexTooLow => write!(f, "AccountIndex too low"),
            Self::AccountIndexTooHigh => write!(f, "AccountIndex too high"),
            Self::NonceTooLow => write!(f, "Nonce too low"),
            Self::ApiKeyIndexTooLow => write!(f, "ApiKeyIndex too low"),
            Self::ApiKeyIndexTooHigh => write!(f, "ApiKeyIndex too high"),
            Self::ExpiredAtInvalid => write!(f, "ExpiredAt invalid"),
            Self::InvalidMarketIndex => write!(f, "MarketIndex invalid"),
            Self::InvalidSignature => write!(f, "Signature invalid"),
            Self::FromAccountIndexTooLow => write!(f, "FromAccountIndex too low"),
            Self::FromAccountIndexTooHigh => write!(f, "FromAccountIndex too high"),
            Self::ToAccountIndexTooLow => write!(f, "ToAccountIndex too low"),
            Self::ToAccountIndexTooHigh => write!(f, "ToAccountIndex too high"),
            Self::AssetIndexTooLow => write!(f, "AssetIndex too low"),
            Self::AssetIndexTooHigh => write!(f, "AssetIndex too high"),
            Self::RouteTypeInvalid => write!(f, "RouteType invalid"),
            Self::TransferAmountTooLow => write!(f, "Transfer amount too low"),
            Self::TransferAmountTooHigh => write!(f, "Transfer amount too high"),
            Self::TransferFeeNegative => write!(f, "Transfer fee negative"),
            Self::TransferFeeTooHigh => write!(f, "Transfer fee too high"),
            Self::WithdrawalAmountTooLow => write!(f, "Withdrawal amount too low"),
            Self::WithdrawalAmountTooHigh => write!(f, "Withdrawal amount too high"),
            Self::PubKeyInvalid => write!(f, "PubKey invalid"),
            Self::ClientOrderIndexTooLow => write!(f, "ClientOrderIndex too low"),
            Self::ClientOrderIndexTooHigh => write!(f, "ClientOrderIndex too high"),
            Self::OrderIndexTooLow => write!(f, "OrderIndex too low"),
            Self::OrderIndexTooHigh => write!(f, "OrderIndex too high"),
            Self::BaseAmountTooLow => write!(f, "BaseAmount too low"),
            Self::BaseAmountTooHigh => write!(f, "BaseAmount too high"),
            Self::PriceTooLow => write!(f, "Price too low"),
            Self::PriceTooHigh => write!(f, "Price too high"),
            Self::IsAskInvalid => write!(f, "IsAsk invalid"),
            Self::OrderTypeInvalid => write!(f, "OrderType invalid"),
            Self::OrderTimeInForceInvalid => write!(f, "OrderTimeInForce invalid"),
            Self::OrderReduceOnlyInvalid => write!(f, "ReduceOnly invalid"),
            Self::OrderTriggerPriceInvalid => write!(f, "TriggerPrice invalid"),
            Self::OrderExpiryInvalid => write!(f, "OrderExpiry invalid"),
            Self::CancelAllTimeInForceInvalid => write!(f, "CancelAllTimeInForce invalid"),
            Self::CancelAllTimeNotInRange => write!(f, "CancelAllTime not in range"),
            Self::BaseAmountsNotEqual => write!(f, "BaseAmounts not equal"),
            Self::BaseAmountNotNil => write!(f, "BaseAmount must be nil"),
            Self::MarketIndexMismatch => write!(f, "MarketIndex mismatch"),
            Self::ClientOrderIndexDuplicate => write!(f, "ClientOrderIndex duplicate"),
            Self::GroupingTypeInvalid => write!(f, "GroupingType invalid"),
            Self::OrderGroupSizeInvalid => write!(f, "OrderGroupSize invalid"),
            Self::InvalidMarginMode => write!(f, "MarginMode invalid"),
            Self::MarginFractionTooLow => write!(f, "MarginFraction too low"),
            Self::MarginFractionTooHigh => write!(f, "MarginFraction too high"),
            Self::InvalidUpdateMarginDirection => write!(f, "UpdateMarginDirection invalid"),
            Self::PoolOperatorFeeInvalid => write!(f, "PoolOperatorFee invalid"),
            Self::PoolStatusInvalid => write!(f, "PoolStatus invalid"),
            Self::InitialSharesTooLow => write!(f, "InitialTotalShares too low"),
            Self::InitialSharesTooHigh => write!(f, "InitialTotalShares too high"),
            Self::MinOperatorShareRateTooLow => write!(f, "MinOperatorShareRate too low"),
            Self::MinOperatorShareRateTooHigh => write!(f, "MinOperatorShareRate too high"),
            Self::MintShareAmountTooLow => write!(f, "MintShareAmount too low"),
            Self::MintShareAmountTooHigh => write!(f, "MintShareAmount too high"),
            Self::BurnShareAmountTooLow => write!(f, "BurnShareAmount too low"),
            Self::BurnShareAmountTooHigh => write!(f, "BurnShareAmount too high"),
            Self::StakeAmountTooLow => write!(f, "StakeAmount too low"),
            Self::StakeAmountTooHigh => write!(f, "StakeAmount too high"),
            Self::UnstakeAmountTooLow => write!(f, "UnstakeAmount too low"),
            Self::UnstakeAmountTooHigh => write!(f, "UnstakeAmount too high"),
            Self::IntegratorAccountIndexTooLow => write!(f, "IntegratorAccountIndex too low"),
            Self::IntegratorAccountIndexTooHigh => write!(f, "IntegratorAccountIndex too high"),
            Self::FeeTooHigh => write!(f, "Fee too high"),
            Self::ApprovalExpiryInvalid => write!(f, "ApprovalExpiry invalid"),
            Self::ApprovalExpiryZeroOnRevocation => write!(f, "ApprovalExpiry must be 0 on revocation"),
            Self::TooManyAttributes => write!(f, "Too many attributes"),
            Self::InvalidAttributeType => write!(f, "Invalid attribute type"),
            Self::AttributeValueOutOfRange => write!(f, "Attribute value out of range"),
            Self::IntegratorAccountIndexRequired => write!(f, "IntegratorAccountIndex required"),
            Self::NonceSkipAttributeInvalid => write!(f, "Nonce skip attribute invalid"),
        }
    }
}

impl std::error::Error for TxError {}
